image: docker:stable

services:
    - docker:stable-dind

.build_image_template: &build_image_definition
    script:
    - docker build -t "${CI_REGISTRY_IMAGE}:${VERSION}" "${IMAGE_PATH}"
    except:
    - master

.build_and_push_image_template: &build_image_push_definition
    script:
    - docker info
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"
    - docker build --build-arg UBUNTU_RELEASE_YEAR=${UBUNTU_RELEASE_YEAR} --build-arg ZED_SDK_MAJOR=${ZED_SDK_MAJOR} --build-arg ZED_SDK_MINOR=${ZED_SDK_MINOR} --build-arg ROS_DISTRO_ARG=${ROS_DISTRO_ARG}                    --build-arg CUDA_MAJOR=${CUDA_MAJOR} --build-arg CUDA_MINOR=${CUDA_MINOR} -t "${CI_REGISTRY_IMAGE}:${VERSION}" "${IMAGE_PATH}"
    - docker tag "${CI_REGISTRY_IMAGE}:${VERSION}" "${CI_REGISTRY_IMAGE}:${VERSION}";
    - docker push "${CI_REGISTRY_IMAGE}"
    only:
    - master

############################

# BUILD and PUSH
##### 3.3
v3.3-cuda10.0-u16-gl_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "gl-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda10.0-u16_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda10.0-u16-run_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "runtime"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition
    
v3.3-cuda10.2-u16-gl_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "2"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "gl-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda10.2-u16_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "2"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda10.2-u16-run_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "2"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "runtime"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.0-u16-gl_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "gl-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.0-u16_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.0-u16-run_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "runtime"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition
    
v3.3-cuda11.1-u16-gl_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "1"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "gl-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.1-u16_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "1"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.1-u16-run_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "1"
        UBUNTU_RELEASE_YEAR: "16"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "runtime"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition
    
# U 18
v3.3-cuda10.0-u18-gl_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "gl-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda10.0-u18_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda10.0-u18-ros_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        ROS_DISTRO_ARG: "melodic"
        IMAGE_VARIANT: "ros-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda10.0-u18-run_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "runtime"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda10.2-u18-gl_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "2"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "gl-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda10.2-u18_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "2"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda10.2-u18-run_push:
    variables:
        CUDA_MAJOR: "10"
        CUDA_MINOR: "2"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "runtime"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.0-u18-gl_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "gl-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.0-u18_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.0-u18-run_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "runtime"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.1-u18-gl_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "1"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "gl-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.1-u18_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "1"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.1-u18-run_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "1"
        UBUNTU_RELEASE_YEAR: "18"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "runtime"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition
    

## U 20

v3.3-cuda11.0-u20_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "20"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.0-u20-gl_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "20"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "gl-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.0-u20-run_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "0"
        UBUNTU_RELEASE_YEAR: "20"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "runtime"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.1-u20_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "1"
        UBUNTU_RELEASE_YEAR: "20"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.1-u20-gl_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "1"
        UBUNTU_RELEASE_YEAR: "20"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "gl-devel"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition

v3.3-cuda11.1-u20-run_push:
    variables:
        CUDA_MAJOR: "11"
        CUDA_MINOR: "1"
        UBUNTU_RELEASE_YEAR: "20"
        ZED_SDK_MAJOR: "3"
        ZED_SDK_MINOR: "3"
        IMAGE_VARIANT: "runtime"
        VERSION: "${ZED_SDK_MAJOR}.${ZED_SDK_MINOR}-${IMAGE_VARIANT}-cuda${CUDA_MAJOR}.${CUDA_MINOR}-ubuntu${UBUNTU_RELEASE_YEAR}.04"
        IMAGE_PATH: "${ZED_SDK_MAJOR}.X/ubuntu/${IMAGE_VARIANT}"
    when: manual
    <<: *build_image_push_definition