version: '2.5.0'
services:
  Ubuntu2004:
    image: "3.7-ros-gl-devel-cuda11.4-ubuntu20.04:latest"
    container_name: ubuntu20
    network_mode: host
    runtime: nvidia
    devices:
      -  /dev/dri:/dev/dri
    restart: always
    volumes:
      - "/etc/group:/etc/group:ro"
      - "/etc/shadow:/etc/shadow:ro"
      - "/etc/sudoers.d:/etc/sudoers.d:ro"
      - "/dev:/dev"
      - "${HOME}/.ssh:/root/.ssh:ro"
      - "/home/behnam:/home/behnam"
    environment:
      - ROS_MASTER_URI=http://172.17.0.1:11311
      - ROS_IP=172.17.0.1
      - ROS_HOSTNAME=172.17.0.1
    privileged: true